-- =====================================================================
-- Migration 0020: BIST sembolleri için investing.com linkleri
-- =====================================================================
-- Piyasa Radarı'nda listelenen her sembolün investing.com sayfasına
-- (özellikle kullanıcı yorumları için) doğrudan tıklanabilmesi gerekiyor.
-- assets master'a 100 BIST sembolünün external_url'i işlenir.
--
-- Mevcut satırlarda yalnızca external_url güncellenir (name korunur);
-- eksik semboller equity_tr olarak yeni satır halinde eklenir. Linkler
-- investing.com slug'ları standart olmadığı için (TUPRS -> tupras,
-- KLKIM -> kalekim-kimyevi-madd) kullanıcı tarafından tek tek verilmiştir.

insert into public.assets (symbol, name, asset_class, currency, exchange, external_url) values
  ('AEFES', 'Anadolu Efes', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/anadolu-efes'),
  ('AKBNK', 'Akbank', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/akbank'),
  ('AKSA', 'Aksa Akrilik', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/aksa'),
  ('AKSEN', 'Aksa Enerji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/aksa-enerji-uretim'),
  ('ALARK', 'Alarko Holding', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/alarko-holding'),
  ('ANSGR', 'Anadolu Sigorta', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/anadolu-sigorta'),
  ('ARCLK', 'Arçelik', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/arcelik'),
  ('ASELS', 'Aselsan', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/aselsan'),
  ('BIMAS', 'BİM Mağazalar', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/bim-magazalar'),
  ('RALYH', 'Ral Yatırım Holding', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/bisas-tekstil'),
  ('BRSAN', 'Borusan Boru', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/borusan-mannesmann'),
  ('BRYAT', 'Borusan Yatırım', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/borusan-yat.-paz.'),
  ('BSOKE', 'Batısöke Çimento', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/batisoke-cimento'),
  ('BTCIM', 'Batıçim', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/bati-cimento'),
  ('CCOLA', 'Coca-Cola İçecek', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/coca-cola-icecek'),
  ('CIMSA', 'Çimsa', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/cimsa'),
  ('DOAS', 'Doğuş Otomotiv', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/dogus-otomotiv'),
  ('DOHOL', 'Doğan Holding', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/dogan-holding'),
  ('ECILC', 'Eczacıbaşı İlaç', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/eczacibasi-ilac'),
  ('EKGYO', 'Emlak Konut GYO', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/emlak-konut-gmyo'),
  ('ENKAI', 'Enka İnşaat', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/enka-insaat'),
  ('EREGL', 'Ereğli Demir Çelik', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/eregli-demir-celik'),
  ('FENER', 'Fenerbahçe Futbol', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/fenerbahce-sportif'),
  ('FROTO', 'Ford Otosan', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/ford-otosan'),
  ('GARAN', 'Garanti Bankası', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/garanti-bankasi'),
  ('GSRAY', 'Galatasaray Sportif', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/galatasaray-sportif'),
  ('GUBRF', 'Gübre Fabrikaları', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/gubre-fabrik.'),
  ('TURSG', 'Güneş Sigorta', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/gunes-sigorta'),
  ('HALKB', 'Halkbank', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/t.-halk-bankasi'),
  ('HEKTS', 'Hektaş', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/hektas'),
  ('TRENJ', 'İpek Doğal Enerji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/ipek-dogal-enerji'),
  ('ISCTR', 'İş Bankası (C)', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/is-bankasi-(c)'),
  ('ISMEN', 'İş Yatırım', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/is-y.-men.-deg.'),
  ('KCHOL', 'Koç Holding', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/koc-holding'),
  ('TRMET', 'Koza Anadolu Metal', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/koza-madencilik'),
  ('TRALT', 'Koza Altın', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/koza-altin'),
  ('KRDMD', 'Kardemir (D)', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/kardemir-(d)'),
  ('MGROS', 'Migros Ticaret', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/migros-ticaret'),
  ('OYAKC', 'Oyak Çimento', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/mardin-cimento'),
  ('OTKAR', 'Otokar', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/otokar'),
  ('PETKM', 'Petkim', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/petkim'),
  ('SAHOL', 'Sabancı Holding', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/sabanci-holding'),
  ('SARKY', 'Sarkuysan', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/sarkuysan'),
  ('SASA', 'Sasa Polyester', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/sasa-polyester'),
  ('SISE', 'Şişe Cam', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/sise-cam'),
  ('SKBNK', 'Şekerbank', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/sekerbank'),
  ('TAVHL', 'TAV Havalimanları', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/tav-havalimanlari'),
  ('TCELL', 'Turkcell', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/turkcell'),
  ('THYAO', 'Türk Hava Yolları', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/turk-hava-yollari'),
  ('TKFEN', 'Tekfen Holding', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/tekfen-holding'),
  ('TOASO', 'Tofaş Oto', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/tofas-oto.-fab.'),
  ('TSKB', 'TSKB', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/t.s.k.b.'),
  ('TTKOM', 'Türk Telekom', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/turk-telekom'),
  ('TUKAS', 'Tukaş', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/tukas'),
  ('TUPRS', 'Tüpraş', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/tupras'),
  ('ULKER', 'Ülker Bisküvi', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/ulker-biskuvi'),
  ('VAKBN', 'VakıfBank', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/vakiflar-bankasi'),
  ('VESTL', 'Vestel', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/vestel'),
  ('AGHOL', 'AG Anadolu Grubu Holding', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/yazicilar-holding'),
  ('YKBNK', 'Yapı Kredi', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/yapi-ve-kredi-bank.'),
  ('ZOREN', 'Zorlu Enerji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/zorlu-enerji'),
  ('KUYAS', 'Kuyumcukent', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/kuyumcukent'),
  ('PGSUS', 'Pegasus', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/pegasus-hava-tasimaciligi'),
  ('ODAS', 'Odaş Elektrik', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/odas-elektrik'),
  ('MAVI', 'Mavi Giyim', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/mavi-giyim-sanayi-ve-ticaret-as'),
  ('ENJSA', 'Enerjisa Enerji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/enerjisa-enerji'),
  ('MPARK', 'MLP Sağlık', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/mlp-saglik'),
  ('SOKM', 'Şok Marketler', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/sok-marketler'),
  ('KONTR', 'Kontrolmatik Teknoloji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/kontrolmatik-teknoloji-enerji-ve-mu'),
  ('TUREX', 'Türeks Turizm', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/tureks-turizm-tasimacilik-as'),
  ('QUAGR', 'Qua Granite', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/qua-granite-hayal'),
  ('CANTE', 'Çan2 Termik', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/can2-termik-as'),
  ('GENIL', 'Gen İlaç', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/gen-ilac-ve-saglik-urunleri'),
  ('GESAN', 'Girişim Elektrik', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/girisim-elektrik-taahhut'),
  ('MAGEN', 'Margün Enerji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/margun-enerji-uretim-sanayi'),
  ('MIATK', 'Mia Teknoloji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/mia-teknoloji-as'),
  ('PSGYO', 'Pasifik GYO', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/pasifik-gayrimenkul-yatirim'),
  ('DAPGM', 'DAP Gayrimenkul', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/dap-gayrimenkul-gelistirme-as'),
  ('GRSEL', 'Gürsel Turizm', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/gursel-turizm-tasimacilik-ve'),
  ('EUREN', 'Europen Endüstri', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/europen-endustri-insaat-sanayi-ve'),
  ('KLRHO', 'Kiler Holding', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/kiler-holding-as'),
  ('ASTOR', 'Astor Enerji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/astor-enerji-as'),
  ('CVKMD', 'CVK Maden', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/cvk-maden-isletmeleri-sanayi-ve'),
  ('EUPWR', 'Europower Enerji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/europower-enerji-ve-otomasyon'),
  ('GRTHO', 'Grainturk Tarım', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/grainturk-tarim-as'),
  ('CWENE', 'CW Enerji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/cw-enerji-muhendislik-ticaret-ve'),
  ('KTLEV', 'Katılımevim Tasarruf Finansman', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/katilimevim-tasarruf-finansman-as'),
  ('PASEU', 'Pasifik Eurasia Lojistik', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/pasifik-eurasia-lojistik-dis'),
  ('IZENR', 'İzdemir Enerji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/izdemir-enerji-elektrik-uretim-as'),
  ('ENERY', 'Enerya Enerji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/enerya-enerji-as'),
  ('REEDR', 'Reeder Teknoloji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/reeder-teknoloji-sanayi-ve-ticaret'),
  ('TABGD', 'TAB Gıda', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/tab-gida-sanayi-ve-ticaret-as'),
  ('PATEK', 'Pasifik Teknoloji', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/pasifik-donanim-ve-yazilim-bilgi'),
  ('OBAMS', 'Oba Makarnacılık', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/oba-makarnacilik-sanayi-ve-ticaret'),
  ('ALTNY', 'Altınay Savunma Teknolojileri', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/altinay-savunma-teknolojileri-as'),
  ('EFOR', 'Efor Çay', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/efor-cay-sanayi-tic-as'),
  ('GLRMK', 'Gülermak', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/gulermak-agir-sanayi-insaat-ve'),
  ('DSTKF', 'Destek Finans Faktoring', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/destek-finans-faktoring-as'),
  ('BALSU', 'Balsu Gıda', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/balsu-gida-sanayi-ve-ticaret-as'),
  ('PAHOL', 'Pasifik Holding', 'equity_tr', 'TRY', 'BIST', 'https://tr.investing.com/equities/pasifik-holding-as')
on conflict (symbol, asset_class) do update
  set external_url = excluded.external_url,
      updated_at   = now();
